name: Push container to ECR

inputs:

  platforms:
    description: 'The platforms to build images for, comma-separated. Valid options are linux/amd64 and linux/arm64.'
    required: true
    default: 'linux/amd64,linux/arm64'

  context:
    description: 'The path to the docker context, if not the root of the repository.'
    required: true
    default: .

  dockerfile:
    description: 'The path to the dockerfile, if not in the root of the repository.'
    required: true
    default: 'Dockerfile'

  ssh:
    description: 'SSH configuration, if needed'
    required: false

on:
  push:
    branches:
      - "main"
  release:
    types:
      - "published"

jobs:
  push-container:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.SANDBOX_DEPLOYMENT_ROLE }}
          aws-region: ${{ variables.SANDBOX_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2


      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          # Build a docker container and
          # push it to ECR so that it can
          # be deployed to ECS.
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT